=== FelixTyrant/Electric-VLSI/trunk/srcj/com/sun/electric/tool/simulation/eventsim/handshakeNet/modelBuilder/ArchSImModel.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!--
   DTD for an archsim model
-->

<!ELEMENT model ((component | connection?)+)>
<!ATTLIST model
	name CDATA #REQUIRED 
>

<!ELEMENT component ( parameter | comment )* >
<!ATTLIST component
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	parameter CDATA #IMPLIED
>

<!ELEMENT connection (comment*, from+, to+, parameter*)>
<!ATTLIST connection
	name CDATA #REQUIRED
>

<!ELEMENT from (comment*) >
<!ATTLIST from
	component CDATA #REQUIRED
	terminal CDATA #REQUIRED
>

<!ELEMENT to ( comment* ) >
<!ATTLIST to
	component CDATA #REQUIRED
	terminal CDATA #REQUIRED
>

<!ELEMENT parameter (comment*) >
<!ATTLIST parameter
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>
                   
<!ELEMENT comment (#PCDATA) >

=== FelixTyrant/Electric-VLSI/srcj/com/sun/electric/tool/simulation/eventsim/handshakeNet/modelBuilder/testModelLoader.xml
<?xml version='1.0' encoding='utf-8'?>

<!-- test for ModelLoader -->

<!DOCTYPE model SYSTEM "ArchSimModel.dtd">

<model name= "first-test">



<component name= "in" type= "B" />
<component name="out" type= "A" />
<component name= "out0" type= "A"/>
<component name= "in0" type= "B"/>
<component name= "in1" type= "B"/>
<component name= "out00" type= "A"/>
<component name= "out01" type= "A"/>
<component name= "inOut00" type= "C"/>
<component name= "inOut01" type= "C"/>

<component name= "in00" type= "B">
<parameter name= "par1" value= "par1" />
<parameter name= "par2" value= "par2"/>
</component>



<connection name= "SINGLE">
	<from component="out" terminal="DATA" />
	<to component="in" terminal="DATA" />
</connection>

<connection name="FORK" >
	<from component="out0" terminal="DATA" />
	
	<to component="in0" terminal="DATA" />	
	<to component= "in1" terminal="DATA" />
</connection>

<connection name="TWOBYTWO" >
	<from component="out00" terminal="DATA" />
	<from component="out01" terminal="DATA" />
	
	<to component="inOut00" terminal="DATA_IN" />
	<to component="inOut01" terminal= "DATA_IN" />
</connection>

<connection name= "FUNNEL">
	<from component= "inOut00" terminal= "DATA_OUT" />
	<from component= "inOut01" terminal="DATA_OUT" />
	
	<to component= "in00" terminal="DATA" />
</connection>

</model>

=== FelixTyrant/Electric-VLSI/srcj/com/sun/electric/tool/simulation/eventsim/handshakeNet/modelBuilder/Example.xml
<?xml version='1.0' encoding='utf-8'?>

<!DOCTYPE model SYSTEM "ArchSimModel.dtd">

<!-- Cell: Example{sch} -->
<!-- Created on Thu May 26, 2005 13:18:29 -->
<!-- Last revised on Fri May 27, 2005 11:46:03 -->
<!-- Written on Fri May 27, 2005 11:47:44 by Electric VLSI Design System, version 8.02o -->

<model name= "Example">

<component name= "in" type= "B" />
<component name= "in0" type= "B" />
<component name= "in00" type= "B" />
<component name= "in1" type= "B" />
<component name= "inOut00" type= "C" />
<component name= "inOut01" type= "C" />
<component name= "out" type= "A" />
<component name= "out0" type= "A" />
<component name= "out00" type= "A" />

<component name= "out01" type= "A" >
	<parameter name= "par1" value= "par1" />
	<parameter name= "par2" value= "par2"/>
</component>

<connection name= "FORK">
	<from component= "out0" terminal="DATA" />
	<to component= "in0" terminal="DATA" />
	<to component= "in1" terminal="DATA" />
</connection>

<connection name= "FUNNEL">
	<from component= "inOut00" terminal="DATA_OUT" />
	<from component= "inOut01" terminal="DATA_OUT" />
	<to component= "in00" terminal="DATA" />
</connection>

<connection name= "SINGLE">
	<from component= "out" terminal="DATA" />
	<to component= "in" terminal="DATA" />
</connection>

<connection name= "TWOBYTWO">
	<from component= "out00" terminal="DATA" />
	<from component= "out01" terminal="DATA" />
	<to component= "inOut00" terminal="DATA_IN" />
	<to component= "inOut01" terminal="DATA_IN" />
</connection>

</model>
